### ISSUE TITLE
Error: DataTableModule is not an NgModule

### ISSUE THREAD

**Issue by isneezy** [afermon/angular-4-data-table-bootstrap-4#2]
Thanks for supporting angular 4 with this wonderful module.
I'm struggling to use it in my angular 4 project, failing with this error

```
@angular/cli: 1.4.2
node: 6.11.3
os: linux x64
@angular/animations: 4.4.1
@angular/common: 4.4.1
@angular/compiler: 4.4.1
@angular/core: 4.4.1
@angular/forms: 4.4.1
@angular/http: 4.4.1
@angular/platform-browser: 4.4.1
@angular/platform-browser-dynamic: 4.4.1
@angular/router: 4.4.1
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.1
@angular/language-service: 4.4.1
typescript: 2.3.4
```

**Comment by milvergithub** [comment]
`ERROR in DataTableModule is not an NgModule
`

**Comment by milvergithub** [comment]
`import {DataTableModule} from 'angular-4-data-table-bootstrap-4/src/index';`

**Comment by isneezy** [comment]
@milvergithub @afermon for now i had to import component by component to a shared module and import the module into the module hat i what to use to work around this issue

**Comment by SalahELGO** [comment]
@isneezy @milvergithub @afermon Here's what I've dont to work this issue around but not sure it's correct:
`@NgModule({
    declarations: [DataTable, DataTableColumn, DataTableRow, DataTablePagination, DataTableHeader],
    exports: [DataTable, DataTableColumn, DataTableRow, DataTablePagination, DataTableHeader]
})`

**Comment by isneezy** [comment]
@SalahELGO can you make a PR?

**Comment by afermon** [comment]
Hi all,

Just updated the package and currently building as expected with Angular 4.4.4

Please take a look at the examples and let me know if that helps!
[Examples repo](https://github.com/afermon/angular-4-data-table-bootstrap-4-demo)
[Live demo](https://afermon.github.io/angular-4-data-table-bootstrap-4-demo/)

**Comment by SalahELGO** [comment]
@afermon Still not working when you do "npm install ..."

the index.d.ts does not have the NgModule decorator.

**Comment by isneezy** [comment]
I'm confirming what @SalahELGO  said. I upgraded to v0.1.1 but it still fails.

**Comment by afermon** [comment]
Hi @SalahELGO, @isneezy can any of you provide a link to your proyect repo or provide more info of your current enviroment?

**Comment by isneezy** [comment]
@afermon I want to collaborate but i don't know how can i help since the repo is private! Any Idea?

**Comment by SalahELGO** [comment]
@afermon I'm working on a private repo too ... and also as @isneezy said, I want to help.
I'll try to describe the problem and the env:
OS: Win7
IDE: VSCode
Angular: ^4.2.4
Angular CLI: 1.2.0
Bootstrap: 4.0.0-beta
fontAwesome: 4.7.0

added angular-4-data-table-bootstrap-4 via Npm: `npm install angular-4-data-table-bootstrap-4 --save`

then, when I build (ng serve): Error: DataTableModule is not an NgModule

so I added to: node_modules/angular-4-data-table-bootstrap-4/dist/index.d.ts:
`@NgModule({
    declarations: [DataTable, DataTableColumn, DataTableRow, DataTablePagination, DataTableHeader],
    exports: [DataTable, DataTableColumn, DataTableRow, DataTablePagination, DataTableHeader]
})`

But it's not viable to do this to an imported module.
I'm not sure but I guess it's the npm install which does not have the bugfix.

**Comment by isneezy** [comment]
Hi I've been able to reproduce this issue using `@angular/cli: 1.4.2`
```sh
ng new ngb-data-table
cd ngb-data-table
npm install angular-4-data-table-bootstrap-4@0.1.1 -S
```

modify `./src/app/app.module.ts` as follows
```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {DataTableModule} from 'angular-4-data-table-bootstrap-4';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule, DataTableModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
then run `ng build`

```js
ERROR in Error: DataTableModule is not an NgModule
    at _getNgModuleMetadata (/home/ivan/repos/ngb-data-table/node_modules/@angular/compiler-cli/src/ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (/home/ivan/repos/ngb-data-table/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/ivan/repos/ngb-data-table/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/home/ivan/repos/ngb-data-table/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/home/ivan/repos/ngb-data-table/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/ivan/repos/ngb-data-table/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/ivan/repos/ngb-data-table/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/ivan/repos/ngb-data-table/node_modules/@ngtools/webpack/src/plugin.js:443:24)
```

I think for now you can publish the npm package using the @SalahELGO work around so we do not have to do it ourselves until we find a better way to solve this problem.

**Comment by afermon** [comment]
@isneezy This is actually due to the angular CLI  (That's why it works in my demo),  it requires modules to use AOT. I will work on it as time permits and update the package.

**Comment by afermon** [comment]
@SalahELGO , @isneezy  Updated the package on Latest commit 0b4656d , v0.2 comes with AOT support and should fix the ng build / serve issue.

**Comment by isneezy** [comment]
Thank you so much for the effort, now it's working perfectly.
