### ISSUE TITLE
cellClick Event not working

### ISSUE THREAD

**Issue by isneezy** [afermon/angular-4-data-table-bootstrap-4#3]
thanks for building this awesome package.
I'm trying to discern clicks on each cell in the table so I can know if I should take the user to see details or just show actions/options for the selected line. I tried unsuccessfully to use the `(cellClick)` event, and at the moment I am using `(rowClick)` and this does not let me know if it comes from `selectColumn` or not

```
<data-table #table [header]="false" (cellClick)="showClient($event)" [indexColumn]="false" [selectColumn]="true" [pagination]="false" [items]="service.items">
 <data-table-column property="name" header="Nome" [sortable]="true"></data-table-column>
 <data-table-column property="email" header="Email" [sortable]="true"></data-table-column>
  <data-table-column property="readableAddress" header="Endereço" [sortable]="true">
    <ng-template #dataTableCell let-item="item">{{item.address.street}} - {{item.address.city}}, {{item.address.country}}</ng-template>
  </data-table-column>
  <data-table-column header="Saldo" [sortable]="true"></data-table-column>
</data-table>
```

**Comment by afermon** [comment]
Hi @isneezy , I just updated the package and added a demo. Please take a look at the examples. 

You may use something like this:
```javascript
DataTableDemo1.prototype.rowClick = function (rowEvent) {
        console.log('Clicked: ' + rowEvent.row.item.name);
    };
```
[Examples repo](https://github.com/afermon/angular-4-data-table-bootstrap-4-demo)
[Live demo](https://afermon.github.io/angular-4-data-table-bootstrap-4-demo/)

**Comment by isneezy** [comment]
Hi, thanks for your effort, but what your suggested is actually what I've been doing so far. what i wanted is to have the ability to detect witch exact column is being clicked, so i checked your source code and find that there where event called `cellClicked` but it wasn't bound to anything so i made a small PR for that.
Thanks in advance!
